name: Profartisans.com
layout_spectrum: 0.09369363593460478
typography_spectrum: 0.4490813693504193
opengraph:
  type: ''
  appId: ''
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/7876355e-10b9-4803-b1a0-041ec7c0c6df.jpg
color:
  brandColors:
    - '#7D8A2E'
    - '#C9D787'
    - '#FFFFFF'
    - '#FFC0A9'
    - '#FF8598'
  brandStrength: 0.21482738546888147
  lightness: 0.49640047516595853
  saturation: 0.7444568065707232
  rhythmicContrast: 0.6724801522867704
title: 'PROFESSIONAL ARTISANS '
description: >-
  ProfArtisans.com provides supervisory functions over Professional Artisans'
  skills delivery in order to create a reliable service delivery to our clients
  and decent Apprenticeship Programmes for the prospective Professional
  Artisans. 
author:
  name: 'Lynays Love World Initiative '
  url: www.profartisans.com
  email: profartisans@live.com
content_rating:
  adult: false
content: []
github: true
